name: Cypress Tests

on: 
  schedule:
    - cron: '0 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STRAVA_USERNAME: ${{ secrets.STRAVA_USERNAME }}
          STRAVA_PW: ${{ secrets.STRAVA_PW }}