name: Cypress Tests

on: [push]
  # schedule:
  #   - cron: '20 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          run: npm run e2e
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STRAVA_USERNAME: ${{ secrets.STRAVA_USERNAME }}
          STRAVA_PW: ${{ secrets.STRAVA_PW }}
